[package]
name = "webserver_helllo_world"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.3"
http-body-util = "0.1.3"
tokio = { version = "1.44.1", features = ["full"] }
tower = "0.5.2"
